### ISSUE TITLE
nuxt.config.js missing?

### ISSUE THREAD

**Issue by husayt** [cosmicjs/nuxt.js-website#1]
seems like `nuxt.config.js` is missing.

Thanks

**Comment by tonyspiro** [comment]
@Atinux any thoughts?

**Comment by atinux** [comment]
@tonyspiro you can add it to the root of the project with this config:

`nuxt.config.js`
```js
module.exports = {
  // nuxt.js config file
  // see https://nuxtjs.org/guide/configuration
}
```

**Comment by tonyspiro** [comment]
Done.  Thanks @Atinux.
